topics:
  estimated_position:
    name: "/odometry/global"
  trajectory_plan:
    name: "/move_base/TEBPlannerROS/global_plan"
  gps_plan:
    name: "/gnss_left/fix"
  waypoints_coords:
    name: "arocs_route.yaml"