topics:
  estimated_position:
    name: "/lego_loam/odom"
  trajectory_plan:
    name: "/move_base/DWAPlannerROS/global_plan"
  gps_plan:
    name: "/reach/fix"
  waypoints_coords:
    name: "simulation_demo.yaml"